name: BIST 15DK Tarama

on:
  schedule:
    # Hafta içi her 15 dakikada bir çalışacak şekilde güncellendi (UTC 07:00 - 15:00)
    - cron: '*/15 7-15 * * 1-5'
  workflow_dispatch:

jobs:
  run-15dk-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Depodan Al
        uses: actions/checkout@v3

      - name: Python Ortamini Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kutuphaneleri Yukle
        run: |
          pip install pandas numpy yfinance requests pytz

      - name: 15 Dakikalik Taramayi Baslat
        run: |
          python bes_dakikalik_tarama.py
