Name: BIST Tarama Botu

on:
  schedule:
    - cron: '*/30 6-15 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tarama_yap:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install --no-cache-dir requests yfinance pandas pytz numpy

      - name: Botu Çalıştır
        run: |
          python main.py

      - name: Hafıza Dosyasını Kaydet ve Push Yap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add borsa_hafiza.json
          git commit -m "Otomatik hafiza guncellemesi [skip ci]" || echo "Degisiklik yok"
          git push
