name: BIST Otomatik Tarama

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalışır
  workflow_dispatch:          # Elle tetiklenebilir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Çek
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir requests yfinance pandas

    - name: Taramayı Çalıştır
      run: python main.py


